### Numpy

In [1]:
import numpy as np

In [2]:
list1=[1,2,3]
np.array(list1)

array([1, 2, 3])

In [3]:
lists=[[9,8,7],[6,5,4],[3,2,1]]
np.array(lists)

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [4]:
np.arange(2,50)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [5]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [9]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [10]:
np.ones(50)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.ones(5,int)

array([1, 1, 1, 1, 1])

In [12]:
np.zeros((3,3),int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [14]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.ones((4,4),int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [16]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [17]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [18]:
np.linspace(100,200,10)

array([100.        , 111.11111111, 122.22222222, 133.33333333,
       144.44444444, 155.55555556, 166.66666667, 177.77777778,
       188.88888889, 200.        ])

In [19]:
np.eye((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [24]:
np.random.rand(3,3)

array([[0.44067651, 0.25393177, 0.20387458],
       [0.84048731, 0.53218947, 0.42750556],
       [0.3052699 , 0.25087958, 0.82694168]])

In [25]:
np.random.randn(1,5)

array([[-0.5944114 , -0.02463653,  0.85331684,  1.62583121, -0.48421002]])

In [26]:
np.random.randint(1,50)

48

In [27]:
np.random.randint(1,100,10)

array([83, 39, 56, 83, 41, 36, 70, 32, 74, 58])

In [28]:
array1=np.arange(50)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [29]:
array1.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [31]:
array1.max()

49

In [32]:
array1.argmax()

49

In [33]:
n=np.eye(6)
n

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [34]:
n.T

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [35]:
n=np.random.rand(3,3)
n

array([[0.95484198, 0.95428111, 0.06236916],
       [0.40674064, 0.81544401, 0.1731744 ],
       [0.87964903, 0.02111039, 0.91407951]])

In [36]:
n.T

array([[0.95484198, 0.40674064, 0.87964903],
       [0.95428111, 0.81544401, 0.02111039],
       [0.06236916, 0.1731744 , 0.91407951]])

In [37]:
array2=np.arange(5,30)
array2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [38]:
array2[0]

5

In [39]:
array2[10:15]

array([15, 16, 17, 18, 19])

In [41]:
array2[0:6]=100
array2

array([100, 100, 100, 100, 100, 100,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29])

In [43]:
subarray=array2[12:21]
subarray

array([17, 18, 19, 20, 21, 22, 23, 24, 25])

In [44]:
subarray[:]=600
subarray

array([600, 600, 600, 600, 600, 600, 600, 600, 600])

In [46]:
matrix1=np.array([[10,20,30],[11,21,31],[12,22,32]])
matrix1

array([[10, 20, 30],
       [11, 21, 31],
       [12, 22, 32]])

In [47]:
matrix1[0:2]

array([[10, 20, 30],
       [11, 21, 31]])

In [50]:
matrix1[2,:]

array([12, 22, 32])

In [51]:
matrix1[1]

array([11, 21, 31])

In [52]:
matrix1[:,(2,2)]

array([[30, 30],
       [31, 31],
       [32, 32]])

In [54]:
array3=np.arange(0,16)
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [55]:
array3+array3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [56]:
np.exp(array3)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

In [57]:
np.sqrt(array3)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [58]:
np.log(array3)

C:\Users\srina\AppData\Local\Temp\ipykernel_20716\2630074268.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(array3)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 ])

In [59]:
np.max(array3)

15

In [60]:
np.min(array3)

0

In [61]:
np.argmax(array3)

15

In [62]:
np.argmin(array3)

0

In [63]:
np.square(array3)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [64]:
np.std(array3)

4.6097722286464435

In [65]:
np.var(array3)

21.25

In [66]:
np.mean(array3)

7.5

In [67]:
n=np.random.randn(4,4)
n

array([[ 0.2753176 , -0.52470523,  0.90942528, -0.21642357],
       [ 1.30716672, -0.34266873,  0.08731227,  0.61381441],
       [ 0.82064368,  0.61339392, -1.86396502,  0.7494221 ],
       [-1.66410121, -0.7265553 , -1.16126516, -0.14615163]])

In [68]:
np.round(n,decimals=2)

array([[ 0.28, -0.52,  0.91, -0.22],
       [ 1.31, -0.34,  0.09,  0.61],
       [ 0.82,  0.61, -1.86,  0.75],
       [-1.66, -0.73, -1.16, -0.15]])

In [69]:
fruits=np.array(['apple','banana','orange','pear','apple'])
np.unique(fruits)

array(['apple', 'banana', 'orange', 'pear'], dtype='<U6')